### ISSUE TITLE
Support for RUT200

### ISSUE THREAD

**Issue by torbenaa** [meri-imperiumi/signalk-teltonika-rutx11#124]
Is RUT200 supported ? I have enabled the plugin, and getting data from networking.lte  and networking.modem.

The pluging status says "Unknown Error", however.

I will happily provide more details if needed.

Thanks !

**Comment by bergie** [comment]
Sounds like it generally works, then. Except for #123

**Comment by torbenaa** [comment]
Ah. And since the RUT200 does not have a GPS module, I guess I will never get rid of that error message.

One can only hope that you will perhaps fail more silently if no GPS data is available. In a future update, that is :)

Thanks for a nice plugins !

**Comment by torbenaa** [comment]
Hi again Henri,

Well - it stops working after a few runs with status "Unknown Error". Then I donøt get any more data from the plugin.

Is there anything I can do to help debug this ?

**Comment by bergie** [comment]
Can you try with release 0.6.0 of this plugin?

**Comment by torbenaa** [comment]
Just did. After unticking the new GPS "Get GPS position from the RUT" option, it works like a charm.
I guess you can add the RUT200 to the hardware compatibility  list :)
Thank you SO much !
