### ISSUE TITLE
TypeError: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by KEGustafsson** [meri-imperiumi/signalk-teltonika-rutx11#3]
Thanks for the plugin!

I have tested this plugin with RUT955 and RUT240. I get this kind of error, but time to time it is working without error and might then stop to this error.

Jun 25 08:09:26 (node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of null at /home/node/.signalk/node_modules/@meri-imperiumi/signalk-teltonika-rutx11/index.js:109:32

Jun 25 08:09:26 (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 688) 

At least RUTX11 and RUT955 modbus interfaces are similar, so it should run on both. I briefly checked RUT240 too and it looks pretty the same, some changes required.

**Comment by sivu** [comment]
I am encountering the same issue

**Comment by KEGustafsson** [comment]
I updated firmware to v7 recently and now I haven't seen the error so far. I'll keep monitoring the situation.
