### ISSUE TITLE
"Cannot read properties of null"

### ISSUE THREAD

**Issue by EdKok** [meri-imperiumi/signalk-teltonika-rutx11#95]
While using "modbus read" from the Linux CLI does work as expected, I get following error in SignalK log:
`TypeError: Cannot read properties of null (reading 'message') at /home/pi/.signalk/node_modules/@meri-imperiumi/signalk-teltonika-rutx11/index.js:169:32`

Using a RUT950 with firmware RUT9XX_R_00.06.09.1
Plugin version 0.4.0

**Comment by EdKok** [comment]
Upgraded to RUT9_R_00.07.02.1 but issue remains.

**Comment by EdKok** [comment]
Updated npm "modbus-stream" to latest (= 8.5.1) but still not working.

**Comment by anhorbc** [comment]
Same here, but with a RUT240 with firmware R_00.07.02.2.

**Comment by eriksnijder** [comment]
Same error in logwith RUT950. Plugin status message gives correct operator and signal strength, but no data is going to Signal K

**Comment by anas10** [comment]
Same error here with a RUT950
```(node:18873) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of null at /data/conf/signalk/node_modules/@meri-imperiumi/signalk-teltonika-rutx11/index.js:169:32```

**Comment by prein2** [comment]
Same problem with a RUTX50, firmware RUTX_R_00.07.04.1
`Apr 24 11:53:34 (node:24089) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of null at /data/conf/signalk/node_modules/@meri-imperiumi/signalk-teltonika-rutx11/index.js:169:32`

**Comment by bergie** [comment]
This is pretty interesting, it is in the catch handler for when we get _some_ error. But we're not getting an error object. I'll add a safety and then we can hopefully find out the _real_ error.

**Comment by bergie** [comment]
Can somebody who had this issue test the `index.js` from git main and verify if the fix helps?

**Comment by prein2** [comment]
The fix helps. Now getting the data in the databrowser. What is strange: in the dashboard the plugin status is 'unknown error', but all works fine now.

**Comment by bergie** [comment]
Yes, I’m unsure which of the data queries fail, but one does. Doesn’t happen on my X11 so hard to debug.
Maybe you could share which SK paths you get from this plugin?

**Comment by prein2** [comment]
These are the signal paths I get :

networking.lte.bars

networking.lte.connectionText

networking.lte.radioQuality

networking.lte.registerNetworkDisplay

networking.lte.rssi

networking.lte.usage.rx

networking.lte.usage.tx

networking.modem.temperature

networking.modem.uptime

I wonder which one is missing


Op 27 apr. 2023 om 21:26 heeft Henri Bergius ***@***.***> het volgende geschreven:

﻿

Yes, I’m unsure which of the data queries fail, but one does. Doesn’t happen on my X11 so hard to debug.
Maybe you could share which SK paths you get from this plugin?

**Comment by EdKok** [comment]
@prein2 I gave up on this plugin and now use node-red with the ModBus patette. Gives me more flexibility to do something with the data as well.

**Comment by eriksnijder** [comment]
The issue is fixed for me. Thx!
